### ISSUE TITLE
Not resetting simulator

### ISSUE THREAD

**Issue by jjnevis** [IconoclastLabs/newclear#7]
Probably something I'm doing wrong, but I'm getting this error:

    35:54: execution error: Can’t get application "iOS Simulator". (-1728)

And the upshot is that the simulator is not reset, all else works though. Hmm, I think the name of the simulator has changed to just "Simulator".

Hang on - I've just noticed the 'reset-sim' gem... might work this out myself!

**Comment by GantMan** [comment]
It's not your fault.  The reset-sim gem has an update.  We'll need the latest reset-sim gem in order to make this work :)

**Comment by GantMan** [comment]
https://github.com/OTGApps/reset-sim/pull/4

**Comment by jjnevis** [comment]
Yep, I noticed the "xcode7_fix" branch!

**Comment by GantMan** [comment]
Ok, can you try pointing at Master?   I've removed the gemfile.lock, so you should be able to update the reset-sim gem without explicitly requiring it.

`gem 'newclear', github 'IconoclastLabs/newclear'`

Now that mark has released v1.1 of reset-sim this should be solved.

**Comment by jjnevis** [comment]
(sorry about the late reply)

Yep, that's working now (although error still showing due to implementation of 'hackish fix', as Mark put it)

**Comment by jjnevis** [comment]
This is really in the wrong place anyway!

**Comment by GantMan** [comment]
I can fix Mark's hackish fix :)  Just wanted to verify before I do a release.

**Comment by jjnevis** [comment]
OK, sorry - I've submitted a pull request OTGApps/reset-sim that changes the AppleScript to check for the app name first, very simple:

https://github.com/OTGApps/reset-sim/pull/5
